# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "mpasternak/focal64-arm"
  #config.vm.box = "scottharwell/fedora-35-aarch64"

  config.vm.network :private_network, ip: "192.168.111.2"
end
