---
# TODO: any way we can run this playbook to upgrade if updates are available? Or is that better solved in other ways?
# TODO: should we set up a private registry as well? docker-registry? looks okay?
# TODO: make a setup to make a k3s setup:
# https://k3s.io/
- name: Setup main k3s server
  hosts: server
  become: true
  
  tasks:
    # set up docker registry
    # TODO: is this optimal if we don't use docker for k3s? (containerd instead). 
    # - name: Install Docker registry
    #   package:
    #     name:
    #       - docker
    #       - docker-registry
    #     state: present

    # - name: Make sure Docker registry is running
    #   service:
    #     name: docker-registry
    #     state: started
    #     enabled: true

    # Set up k3s master
    # TODO: how to make the curl stuff idempotent? Check for file existence? 
    - name: Install k3s
      shell: >
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
      environment:
        INSTALL_K3S_NAME: server
        K3S_KUBECONFIG_MODE: 644
        K3S_NODE_NAME: main

    - name: Make sure k3s is active
      service:
        name: k3s-server
        state: started
        enabled: true

    # TODO: any more k8s config? storage providers and other things that make life easier later?

    # TODO: any better way we can handle this?
    - name: Save access token for later use
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    # TODO: any better way to do this? any access policy ctl program to use?
    # TODO: any idempotency issues?
    # TODO: now we have to do manual work to get it 
    - name: Fetch k3s file to easily be able to connect
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: k3s-config


- name: Set up k3s worker node
  hosts: worker
  become: true

  tasks:
    # TODO: actually make it fail it shell command fails... now it just say changed and does nothing
    - name: Install k3s (as a worker/agent)
      shell: >
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
      environment:
        # TODO: any clever ways to make unique names for the workers here?
        INSTALL_K3S_NAME: worker
        K3S_NODE_NAME: worker
        K3S_URL: "https://{{ hostvars[groups['server'][0]]['ansible_default_ipv4'] }}:6443"
        K3S_TOKEN: "{{ hostvars[groups['server'][0]]['k3s_token'] }}"
        
    - name: Make sure k3s is active
      service:
        name: k3s-worker
        state: started
        enabled: true
