name: Validate Ansible playbooks

on: [push, pull_request]

jobs:
  validate:
    # TODO: consider making this more dynamic
    strategy:
      matrix:
        directory:
          - ftp-server
          - kubernetes-k3s

    name: Validate ${{ matrix.directory }}
          
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Ansible and dependencies
        run: |
          pip install ansible ansible-lint yamllint molecule[docker]==3.5.2 docker
      - name: Validate yaml files
        working-directory: ${{ matrix.directory }}
        run: |
          yamllint *.yml
      - name: Syntax check Ansible playbook
        working-directory: ${{ matrix.directory }}
        run: |
          ansible-playbook playbook.yml --syntax-check
      - name: Lint Ansible playbook
        working-directory: ${{ matrix.directory }}
        run: |
          ansible-lint playbook.yml
      # TODO: any way we can make it clear this is skipped if molecule folder does not exist? 
      - name: Molecule tests (if exists)
        working-directory: ${{ matrix.directory }}
        run: |
          test ! -d molecule || molecule test
